import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ToolContext } from "../context.js";
import { registerSendMessage } from "./send-message.js";
import { registerBroadcast } from "./broadcast.js";
import { registerCreateScenario } from "./create-scenario.js";
import { registerEnrollScenario } from "./enroll-scenario.js";
import { registerManageTags } from "./manage-tags.js";
import { registerCreateForm } from "./create-form.js";
import { registerCreateTrackedLink } from "./create-tracked-link.js";
import { registerCreateRichMenu } from "./create-rich-menu.js";
import { registerListFriends } from "./list-friends.js";
import { registerGetFriendDetail } from "./get-friend-detail.js";
import { registerGetFormSubmissions } from "./get-form-submissions.js";
import { registerGetLinkClicks } from "./get-link-clicks.js";
import { registerAccountSummary } from "./account-summary.js";
import { registerListCrmObjects } from "./list-crm-objects.js";
import { registerManageAdPlatforms } from "./manage-ad-platforms.js";
import { registerGetConversionLogs } from "./get-conversion-logs.js";
import { registerManageStaff } from "./manage-staff.js";
import { registerUploadImage } from "./upload-image.js";
import { registerManageFriends } from "./manage-friends.js";
import { registerManageScenarios } from "./manage-scenarios.js";
import { registerManageBroadcasts } from "./manage-broadcasts.js";
import { registerManageRichMenus } from "./manage-rich-menus.js";
import { registerManageForms } from "./manage-forms.js";
import { registerManageTrackedLinks } from "./manage-tracked-links.js";
import { registerManageAutoReplies } from "./manage-auto-replies.js";
import { registerManageTrafficPools } from "./manage-traffic-pools.js";
import { registerManageMessageTemplates } from "./manage-message-templates.js";
import { registerListConversations } from "./list-conversations.js";
import { registerGetConversation } from "./get-conversation.js";

export function registerAllTools(server: McpServer, ctx: ToolContext): void {
  registerSendMessage(server, ctx);
  registerBroadcast(server, ctx);
  registerCreateScenario(server, ctx);
  registerEnrollScenario(server, ctx);
  registerManageTags(server, ctx);
  registerCreateForm(server, ctx);
  registerCreateTrackedLink(server, ctx);
  registerCreateRichMenu(server, ctx);
  registerListFriends(server, ctx);
  registerGetFriendDetail(server, ctx);
  registerGetFormSubmissions(server, ctx);
  registerGetLinkClicks(server, ctx);
  registerAccountSummary(server, ctx);
  registerListCrmObjects(server, ctx);
  registerManageAdPlatforms(server, ctx);
  registerGetConversionLogs(server, ctx);
  registerManageStaff(server, ctx);
  registerUploadImage(server, ctx);
  registerManageFriends(server, ctx);
  registerManageScenarios(server, ctx);
  registerManageBroadcasts(server, ctx);
  registerManageRichMenus(server, ctx);
  registerManageForms(server, ctx);
  registerManageTrackedLinks(server, ctx);
  registerManageAutoReplies(server, ctx);
  registerManageTrafficPools(server, ctx);
  registerManageMessageTemplates(server, ctx);
  registerListConversations(server, ctx);
  registerGetConversation(server, ctx);
}
